name: Auto Build & Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Auto-commit changes (biar git bersih)
      - name: Commit pending changes
        run: |
          git config user.name "Hyun09"
          git config user.email "hyun@example.com"
          git add -A
          git commit -m "chore: auto-commit before version bump" || echo "No changes to commit"

      # 5. Bump version & create tag
      - name: Bump version & push tag
        shell: bash
        run: |
          git config user.name "Hyun09"
          git config user.email "hyun@example.com"
          VERSION=$(npm version patch -m "Release v%s")
          echo "New version: $VERSION"
          git push origin main --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 6. Show latest tag
      - name: Show latest tag
        run: git describe --tags

      # 7. Build app with electron-builder
      - name: Build Electron App
        run: npm run dist -- --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 8. Upload artifacts ke GitHub Release
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.exe
            dist/latest.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
