name: Auto Build & Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Auto-commit pending changes
      - name: Commit pending changes
        run: |
          git config user.name "Hyun09"
          git config user.email "hyun@example.com"
          git add -A
          git diff --cached --quiet || git commit -m "chore: auto-commit before version bump"

      # 5. Bump version & create tag
      - name: Bump version & push tag
        id: version_bump
        shell: bash
        run: |
          git config user.name "Hyun09"
          git config user.email "hyun@example.com"
          VERSION=$(npm version patch -m "Release v%s")
          echo "new_tag=$VERSION" >> $GITHUB_OUTPUT
          git push origin main --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 6. Build app with electron-builder
      - name: Build Electron App
        run: npm run dist -- --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 7. Upload artifacts ke GitHub Release pakai tag
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version_bump.outputs.new_tag }}
          files: |
            dist/*.exe
            dist/latest.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
